spring:
  config:
    import: optional:file:.env[.properties]

  output:
    ansi:
      enabled: ALWAYS

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.sql

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

api:
  security:
    token:
      secret: ${SECRET}
