spring:
  output:
    ansi:
      enabled: ALWAYS

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql

  datasource:
    url: jdbc:postgresql://localhost:5432/database
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: validate

api:
  security:
    token:
      secret: "SECRET"