spring:
  output:
    ansi:
      enabled: ALWAYS

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql

  datasource:
    url: jdbc:h2:mem:db;MODE=PostgreSQL;
    driverClassName: org.h2.Driver
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: validate

api:
  security:
    token:
      secret: "SECRET"