spring:
  output:
    ansi:
      enabled: ALWAYS

  liquibase:
    enabled: false

  datasource:
    url: jdbc:h2:mem:db;MODE=PostgreSQL;
    driverClassName: org.h2.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

api:
  security:
    token:
      secret: ${SECRET}